name: Build and Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # needed for tag/version

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install package
        run: |
          python -m pip install .[docs]

      - name: Build Documentation
        working-directory: ./docs
        run: |
          make html

      - name: Deploy on gh-pages 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html 
